In [55]:
import pandas as pd
import numpy as np

# Exception Handling if the file is not found
try: 
    df = pd.read_csv('BD_Weather_Data.csv')
except FileNotFoundError:
    print("Error:Dataset file was not found.")
else:
    print("Dataset imported successfully!")
finally:
    print("File import step completed")

Dataset imported successfully!
File import step completed

In [29]:
df.head(10)

,time,temperature_2m,relative_humidity_2m,rain,pressure_msl,cloud_cover,wind_speed_100m,wind_direction_100m,soil_temperature_100_to_255cm,city
0,2015-12-31T00:00,14.0,96,0.0,1017.6,77,11.2,2,24.7,Dhaka
1,2015-12-31T01:00,14.0,96,0.0,1017.3,79,12.0,7,24.7,Dhaka
2,2015-12-31T02:00,13.4,95,0.0,1017.1,91,12.5,18,24.7,Dhaka
3,2015-12-31T03:00,13.6,95,0.0,1017.0,90,12.4,26,24.7,Dhaka
4,2015-12-31T04:00,13.6,97,0.0,1016.7,99,11.2,50,24.7,Dhaka
5,2015-12-31T05:00,13.6,97,0.0,1016.4,100,11.3,63,24.7,Dhaka
6,2015-12-31T06:00,14.9,93,0.0,1017.6,100,9.9,71,24.7,Dhaka
7,2015-12-31T07:00,15.1,93,0.0,1018.5,99,8.4,65,24.7,Dhaka
8,2015-12-31T08:00,17.4,88,0.0,1019.7,97,7.5,55,24.7,Dhaka
9,2015-12-31T09:00,17.1,89,0.0,1020.1,91,5.9,47,24.7,Dhaka

In [30]:
# Display of the last 5 rows and 5 random sample rows
print("The Last 5 rows:")
print(df.tail(5))
print("\nRandom Sample of 5 rows")
print(df.sample(5))

The Last 5 rows:
                    time  temperature_2m  relative_humidity_2m  rain  \
350875  2026-01-01T19:00            17.6                    78   0.0
350876  2026-01-01T20:00            15.8                    84   0.0
350877  2026-01-01T21:00            14.9                    88   0.0
350878  2026-01-01T22:00            14.5                    90   0.0
350879  2026-01-01T23:00            13.2                    92   0.0

        pressure_msl  cloud_cover  wind_speed_100m  wind_direction_100m  \
350875        1013.1            0              8.0                  312
350876        1014.1            0              8.0                  310
350877        1014.6            0              8.8                  311
350878        1015.2            0             10.4                  316
350879        1014.9            0             12.6                  323

        soil_temperature_100_to_255cm      city
350875                           24.6  Rajshahi
350876                           24.6  Rajshahi
350877                           24.6  Rajshahi
350878                           24.6  Rajshahi
350879                           24.6  Rajshahi

Random Sample of 5 rows
                    time  temperature_2m  relative_humidity_2m  rain  \
325171  2023-01-26T19:00            24.2                    71   0.0
62252   2023-02-05T20:00            18.9                    86   0.0
172876  2025-09-17T04:00            25.8                    94   1.2
133585  2021-03-25T01:00            27.4                    84   0.0
205446  2019-06-03T06:00            26.0                    90   0.5

        pressure_msl  cloud_cover  wind_speed_100m  wind_direction_100m  \
325171        1012.6            0             11.2                  327
62252         1012.0            0             17.1                  298
172876        1008.2          100             10.1                  197
133585        1008.7            0             14.3                  260
205446        1006.4           93              8.6                   68

        soil_temperature_100_to_255cm        city
325171                           22.2    Rajshahi
62252                            22.8       Dhaka
172876                           28.2  Chittagong
133585                           24.6  Chittagong
205446                           24.5      Sylhet

In [31]:
# To check the total rows/columns and view all column names
print("Dataset Shape (Rows, Columns):", df.shape)
print("Column Names:" , df.columns)

Dataset Shape (Rows, Columns): (350880, 10)
Column Names: Index(['time', 'temperature_2m', 'relative_humidity_2m', 'rain',
       'pressure_msl', 'cloud_cover', 'wind_speed_100m', 'wind_direction_100m',
       'soil_temperature_100_to_255cm', 'city'],
      dtype='object')

In [32]:
# Column Datatypes and Whole Dataset Information
print("Data Types\n:" , df.dtypes)
print("\nDataset Info:")
df.info()

Data Types
: time                              object
temperature_2m                   float64
relative_humidity_2m               int64
rain                             float64
pressure_msl                     float64
cloud_cover                        int64
wind_speed_100m                  float64
wind_direction_100m                int64
soil_temperature_100_to_255cm    float64
city                              object
dtype: object

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350880 entries, 0 to 350879
Data columns (total 10 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   time                           350880 non-null  object
 1   temperature_2m                 350880 non-null  float64
 2   relative_humidity_2m           350880 non-null  int64
 3   rain                           350880 non-null  float64
 4   pressure_msl                   350880 non-null  float64
 5   cloud_cover                    350880 non-null  int64
 6   wind_speed_100m                350880 non-null  float64
 7   wind_direction_100m            350880 non-null  int64
 8   soil_temperature_100_to_255cm  350880 non-null  float64
 9   city                           350880 non-null  object
dtypes: float64(5), int64(3), object(2)
memory usage: 26.8+ MB

In [33]:
# Statistical Summary of the Dataset
df.describe()

,temperature_2m,relative_humidity_2m,rain,pressure_msl,cloud_cover,wind_speed_100m,wind_direction_100m,soil_temperature_100_to_255cm
count,350880.000000,350880.000000,350880.000000,350880.000000,350880.000000,350880.000000,350880.00000,350880.000000
mean,25.729029,80.384661,0.291787,1008.665861,51.493704,12.958080,184.50963,25.826507
std,5.027464,13.656795,0.945737,5.555416,41.252592,7.762477,99.17757,2.482051
min,7.100000,10.000000,0.000000,983.500000,0.000000,0.000000,0.00000,20.400000
25%,22.600000,73.000000,0.000000,1004.300000,6.000000,6.900000,112.00000,23.600000
50%,26.900000,84.000000,0.000000,1008.900000,51.000000,11.600000,175.00000,26.500000
75%,29.100000,91.000000,0.100000,1013.200000,98.000000,17.700000,268.00000,28.000000
max,41.800000,100.000000,32.500000,1023.400000,100.000000,80.300000,360.00000,29.700000

### Cleaning the Dataset

In [34]:
# Check for missing values in the column and total missing values in the dataset
print("Missing values in each column:")
df.isnull().sum()

Missing values in each column:

time                             0
temperature_2m                   0
relative_humidity_2m             0
rain                             0
pressure_msl                     0
cloud_cover                      0
wind_speed_100m                  0
wind_direction_100m              0
soil_temperature_100_to_255cm    0
city                             0
dtype: int64

In [35]:
print("Total missing values in the Dataset")
df.isnull().sum().sum()

Total missing values in the Dataset

np.int64(0)

In [36]:
# Check total number of duplicate rows
df.duplicated().sum()

np.int64(0)

In [37]:
# To Remove any missing values and duplicate rows
df = df.dropna()
df = df.drop_duplicates()

In [38]:
# Clean messy text in the city column
df['city'] = df['city'].str.strip().str.title()
print("Unique Cities:", df['city'].unique())

Unique Cities: ['Dhaka' 'Chittagong' 'Sylhet' 'Rajshahi']

In [39]:
# Creating a speparate column for time and dropping the time from the dataset
df['date'] = pd.to_datetime(df['time']).dt.date
df['date'] = pd.to_datetime(df['date'])
df = df.drop(columns=['time'])
df.head()

,temperature_2m,relative_humidity_2m,rain,pressure_msl,cloud_cover,wind_speed_100m,wind_direction_100m,soil_temperature_100_to_255cm,city,date
0,14.0,96,0.0,1017.6,77,11.2,2,24.7,Dhaka,2015-12-31
1,14.0,96,0.0,1017.3,79,12.0,7,24.7,Dhaka,2015-12-31
2,13.4,95,0.0,1017.1,91,12.5,18,24.7,Dhaka,2015-12-31
3,13.6,95,0.0,1017.0,90,12.4,26,24.7,Dhaka,2015-12-31
4,13.6,97,0.0,1016.7,99,11.2,50,24.7,Dhaka,2015-12-31

### Remaning the Column names

In [40]:
df = df.rename(columns={
    'date': 'Date',
    'temperature_2m' : 'Temp',
    'relative_humidity_2m' : 'Humidity',
    'rain' : 'Rain',
    'pressure_msl' : 'Pressure',
    'cloud_cover' : 'CloudCover',
    'wind_speed_100m' : 'WindSpeed',
    'wind_direction_100m' : 'WindDir',
    'soil_temperature_100_to_255cm' : 'SoilTemp',
    'city' : 'City'
    })
df.head()

,Temp,Humidity,Rain,Pressure,CloudCover,WindSpeed,WindDir,SoilTemp,City,Date
0,14.0,96,0.0,1017.6,77,11.2,2,24.7,Dhaka,2015-12-31
1,14.0,96,0.0,1017.3,79,12.0,7,24.7,Dhaka,2015-12-31
2,13.4,95,0.0,1017.1,91,12.5,18,24.7,Dhaka,2015-12-31
3,13.6,95,0.0,1017.0,90,12.4,26,24.7,Dhaka,2015-12-31
4,13.6,97,0.0,1016.7,99,11.2,50,24.7,Dhaka,2015-12-31

## Data Analysis

### Why We Group and Save the Data (Cell 13)
* **Hourly to Daily Data:** The original dataset has 24 hourly rows for every single day (350,880 rows total). After removing the time part, the same `Date` and `City` appear 24 times for each day.
* **Grouping (`groupby` & `mean`):** We group the rows by `Date` and `City` and calculate the daily average (`mean()`) so that each city has **only 1 clean summary record per day** (reducing 350,880 hourly rows to 14,620 daily rows).
* **Sorting & Saving (`sort_values` & `to_csv`):** Finally, we sort the records in calendar order and save them to a new file (`BD_Weather_Cleaned.csv`). This keeps our original dataset safe while giving our application a clean daily CSV file to load, analyze, and update.

In [41]:
# Group hourly rows into daily city averages, sort by Date, and save to a new CSV
df = df.groupby(['Date', 'City'], as_index=False).mean().round(2)
df = df.sort_values(by=['Date', 'City']).reset_index(drop=True)
df.to_csv('BD_Weather_Cleaned.csv', index=False)
df.head(10)

,Date,City,Temp,Humidity,Rain,Pressure,CloudCover,WindSpeed,WindDir,SoilTemp
0,2015-12-31,Chittagong,18.88,85.62,0.0,1017.82,59.42,7.14,227.33,23.10
1,2015-12-31,Dhaka,17.91,83.38,0.0,1018.00,52.75,8.57,179.12,24.68
2,2015-12-31,Rajshahi,18.02,79.04,0.0,1018.25,30.08,8.55,204.79,24.89
3,2015-12-31,Sylhet,18.47,81.00,0.0,1018.07,47.00,4.69,134.00,23.54
4,2016-01-01,Chittagong,19.04,83.79,0.0,1018.79,30.38,10.93,199.71,23.01
5,2016-01-01,Dhaka,18.72,81.12,0.0,1019.09,8.21,8.11,300.04,24.59
6,2016-01-01,Rajshahi,18.17,80.12,0.0,1019.43,0.54,10.86,314.54,24.79
7,2016-01-01,Sylhet,18.58,79.17,0.0,1019.20,3.38,6.25,171.17,23.45
8,2016-01-02,Chittagong,19.38,80.83,0.0,1018.02,1.17,13.02,201.04,23.00
9,2016-01-02,Dhaka,18.43,84.54,0.0,1018.27,25.75,7.69,214.38,24.50

In [42]:
# Calculate overall statistical analysis uisng Pandas mean, median, max, min, sum and standard deviation
print("Mean Temperatue:", round(df['Temp'].mean(),2))
print("Meadian Temperatue:", round(df['Temp'].median(),2))
print("Max Temperatue:", df['Temp'].max())
print("Min Temperatue:", df['Temp'].min())
print("Total Rainfall:", round(df['Rain'].sum(),2))
print("Standard Deviation of Temperatue:", round(df['Temp'].std(),2))

Mean Temperatue: 25.73
Meadian Temperatue: 27.2
Max Temperatue: 34.3
Min Temperatue: 12.35
Total Rainfall: 4264.95
Standard Deviation of Temperatue: 4.24

In [43]:
# City Wise Average temperature and total rainfall in decending order
CitySummary = df.groupby('City')[['Temp','Humidity','SoilTemp']].mean().round(2)
CityRain = df.groupby('City')['Rain'].sum().round(2)

print("Average Weather By City:\n", CitySummary.sort_values(by='Temp', ascending=False))
print("\nTotal Rainfall by City\n",CityRain.sort_values(ascending=False))

Average Weather By City:
              Temp  Humidity  SoilTemp
City
Chittagong  25.98     80.82     26.14
Rajshahi    25.96     78.21     26.18
Dhaka       25.89     80.29     26.26
Sylhet      25.09     82.22     24.73

Total Rainfall by City
 City
Sylhet        1824.90
Chittagong    1040.70
Dhaka          776.47
Rajshahi       622.88
Name: Rain, dtype: float64

### Use Of NumPy Library as per Project Reruirement:
* Part 2: Use NumPy to calculate summaries from records or numerical values
* Part 6: Numpy: Arrays and numerical summaries such as totals, averages, minimum/maximum, median, or standard deviation. 
* Part 6: Importing a library is not sufficient. Demonstrate how it contributes to the application"

Advantage of using Numpy Arrays over list:
* Standard Python Lists do not have built-in .mean(), .median(), or .std() functions.
* NumPy arrays calculate all of these in one simple line and run much faster on large datasets.

In [44]:
# Function to calculate weather statistics for a city using NumPy Arrays
def CalculateCityStats (Dataframe , CityName):
    CityData = Dataframe[Dataframe['City'] == CityName]

    if len(CityData) == 0:
        print("No data found for" , CityName)
        return
    
    TempArray = np.array(CityData['Temp'])
    RainArray = np.array(CityData['Rain'])
    HumidityArray = np.array(CityData['Humidity'])
    SoilArray = np.array(CityData['SoilTemp'])

    print("NumPy Weather Statistics for:" , CityName)
    print("Average Temperature:" , round(np.mean(TempArray),2))
    print("Maximum Temperature:" , round(np.max(TempArray),2))
    print("Minimum Temperature:" , round(np.min(TempArray),2))
    print("Standard Deviation of  Temperature:" , round(np.std(TempArray),2))
    print("Total Rainfall:" , round(np.sum(RainArray),2))
    print("Average Humidity:" , round(np.mean(HumidityArray),2))
    print("Average Soil Temperature:" , round(np.mean(SoilArray),2))
    print()

# Test the Function for City:
CalculateCityStats(df ,'Dhaka')
CalculateCityStats(df ,'Sylhet')

NumPy Weather Statistics for: Dhaka
Average Temperature: 25.89
Maximum Temperature: 33.9
Minimum Temperature: 13.56
Standard Deviation of  Temperature: 4.37
Total Rainfall: 776.47
Average Humidity: 80.29
Average Soil Temperature: 26.26

NumPy Weather Statistics for: Sylhet
Average Temperature: 25.09
Maximum Temperature: 33.04
Minimum Temperature: 13.52
Standard Deviation of  Temperature: 4.2
Total Rainfall: 1824.9
Average Humidity: 82.22
Average Soil Temperature: 24.73

### Tuple For GUI Display

In [45]:
# For GUI Define fixed Tuples for allowed cities and main menu Option:
AllowedCities = ('Dhaka' , 'Chittagong' , 'Sylhet', 'Rajshahi')

MenuOptions = (
    '1. View Weather Records',
    '2. Add New Weather Record',
    '3. Search Weather Records',
    '4. Update Weather Record',
    '5. Delete Weather Record',
    '6. City Weather Statistics (By NumPy)',
    '7. Save Records to CSV',
    '8. Exit'
)
print ("Allowed Cities Tuple", AllowedCities)

Allowed Cities Tuple ('Dhaka', 'Chittagong', 'Sylhet', 'Rajshahi')

## Object Oriented Programming
- Class Representing a single daily weather record
- __ init __ : Stands for initilize. Built in constructor in Python
- self: refres to this object. In C language it is 'this' keyword
- def ToDict(self): A method that packs all the object's stored values into a Python Dictionary. This makes easy for Pandas to convert list of objects into DataFrame or CSV File.

In [46]:
class WeatherRecord:
    # Initializing the object values using the constructor
    def __init__(self, Date, City,Temp,Humidity,Rain,Pressure,CloudCover,WindSpeed, WindDir,SoilTemp):
        self.Date = str(Date)
        self.City = City
        self.RecordId = City + '_' + self.Date
        self.Temp = Temp
        self.Humidity = Humidity
        self.Rain = Rain
        self.Pressure = Pressure
        self.CloudCover = CloudCover
        self.WindSpeed = WindSpeed
        self.WindDir = WindDir
        self.SoilTemp = SoilTemp
        self.Status = self.GetWeatherStatus()

    def GetWeatherStatus(self):
        if self.Rain >= 2.0:
            return "Heavy Rain"
        elif self.Temp >= 32.0:
            return "Heat Wave! Very hot temperature!"
        elif self.WindSpeed >= 25.0:
            return "High Wind!"
        else:
            return "Normal Weather Condition"

    def ToDict(self):
        return{
            'Date' : self.Date,
            'City' : self.City,
            'Temp' : self.Temp,
            'Humidity' : self.Humidity,
            'Rain' : self.Rain,
            'Pressure' : self.Pressure,
            'CloudCover' : self.CloudCover,
            'WindSpeed' : self.WindSpeed,
            'WindDir' : self.WindDir,
            'SoilTemp' : self.SoilTemp,
            'Status' : self.Status
        }

### User input , Validation and Exception Handling:

In [47]:
def GetValidFloat(UserInput, MinVal, MaxVal):
    while True:
        try:
            Value = float(input(UserInput))
        except ValueError:
            print("Invalid input! Please enter a valid number.")
        else:
            if Value >= MinVal and Value <= MaxVal:
                return Value
            else:
                print("Value must be between", MinVal, "and", MaxVal)
        finally:
            pass

def GetValidCity():
    while True:
        CityInput = input("Enter City (Dhaka, Chittagong, Sylhet, Rajshahi:) ").strip().title()
        if CityInput in AllowedCities:
            return CityInput
        else:
            print("Invalid City! Please choose from:", AllowedCities)

def GetValidDate():
    while True:
        DateInput= input('Enter Date (YYYY-MM-DD): ').strip()
        
        # Check if date has 10 characters and hyphens (-) at index 4 and 7 (YYYY-MM-DD)
        if len(DateInput)==10 and DateInput[4] == '-' and DateInput[7] == '-': 
            return DateInput
        
        else:
            print("Invalid format! Please use YYYY-MM-DD (eg. 2023-05-05)")

### Functions to load and save weather records using a CSV file:
- File Functions and Persistent Data

### File Handling Functions: Load and Save Records (Cell 20)
* **`LoadRecordsFromCsv()`:** Reads `BD_Weather_Cleaned.csv` using Pandas inside a `try-except-else-finally` block. It loops through every row, converts each row into a `WeatherRecord` object, and stores all objects inside a Python **List** (`RecordsList`).
* **`SaveRecordsToCsv(RecordsList)`:** Converts all `WeatherRecord` objects back into dictionaries using `.ToDict()`, creates a Pandas DataFrame, and saves the updated data to `BD_Weather_Cleaned.csv` so changes are permanently stored.

In [48]:
def LoadRecordsFromCsv():
    RecordsList = []
    try:
        LoadedDf = pd.read_csv('BD_Weather_Cleaned.csv')
    except FileNotFoundError:
        print("Error: CSV file not found.")
    else:
        # Convert into table rows into a list of dictionaries and create object
        RowList = LoadedDf.to_dict('records')
        for Row in RowList:
            Record = WeatherRecord(
                Row['Date'], Row['City'], Row['Temp'], Row['Humidity'], 
                Row['Rain'], Row['Pressure'], Row['CloudCover'], 
                Row['WindSpeed'], Row['WindDir'], Row['SoilTemp']
            )
            RecordsList.append(Record)
        print("Total records loaded:", len(RecordsList))
    finally:
        print("Total process finished.")
    return RecordsList


# Function to Save records:
def SaveRecordsToCsv(RecordsList):
    try:
        DictList = []
        for Record in RecordsList:
            DictList.append(Record.ToDict())
        SaveDf = pd.DataFrame(DictList)
        SaveDf.to_csv('BD_Weather_Cleaned.csv',index=False)
    except Exception:
        print("Error: Could not sace the file.")
    else:
        print("Total records saved", len(RecordsList))
    finally:
        print("Save Process Finished")

### Manager Class:
Objectives:

__Part 1__:
- Initialize records list
- View records
- Add new records

__Part 2__:
- Search
- Update
- Delete
- Analyze
- Save Methods

In [49]:
# Part 1:
class WeatherManager:
    def __init__(self):
        #Load all weather objects into python List
        # self.Records = LoadRecordsFromCsv()
        self.Records = LoadRecordsFromCsv()

    def ViewRoceords(self):
        # Convert first 10 objects to dictionaries and display as a Pandas table
        SampleList = []
        for Record in self.Records[:10]:
            SampleList.append(Record.ToDict())
        ViewDf = pd.DataFrame(SampleList)
        print("Showing First 10 Weather Records")
        print(ViewDf)

    def AddRecord(self):
        print("Add New Weather Rocord")
        Date = GetValidDate()
        City = GetValidCity()
        NewId = City + "_" + Date

        # Check if the new RecordId already exsists in the list to prevent duplicates
        for Record in self.Records:
            if Record.RecordId == NewId:
                print("Error: A record for", City, "on", Date, "already exsists!")
                return

        Temp = GetValidFloat("Enter Temperature (-10 to 55): ", -10 ,55)
        Humidity = GetValidFloat("Enter Humidity (0 to 100)", 0, 100)
        Rain = GetValidFloat("Enter Rainfall (0 to 500)", 0, 500)
        Pressure = GetValidFloat("Enter Pressure (900 to 1100)", 900, 1100)
        CloudCover = GetValidFloat("Enter Cloud Cover (0 to 100)", 0, 100)
        WindSpeed = GetValidFloat("Enter Wind Speed (0 to 200)", 0, 200)
        WindDir = GetValidFloat("Enter Wind Direction (0 to 360)", 0, 360)
        SoilTemp = GetValidFloat("Enter Soil Temperature (-5 to 50)", -5, 50)

        NewRecord = WeatherRecord(Date,City,Temp,Humidity,Rain,Pressure,CloudCover,WindSpeed,WindDir,SoilTemp)
        self.Records.append(NewRecord)
        print("Success! New Record has been added for", City, "on" , Date)

### OOP Principle:
Inheritance (Class inherits attributes and methods from a parent class inside the parentheses)

In [50]:
# Part 2

class WeatherManager(WeatherManager):
    def SearchRecord(self):
        print("Search for Weather Record")
        Date = GetValidDate()
        City = GetValidCity()
        SearchId = City + "_" + Date

        for Record in self.Records:
            if Record.RecordId == SearchId:
                print("Record Found:", Record.ToDict())
                return
        print("Error: No record found for", City, "on", Date)

    def UpdateRecord(self):
        print("Update Weather Record")
        Date = GetValidDate()
        City = GetValidCity()
        TargetId = City + "_" + Date

        for Record in self.Records:
            if Record.RecordId == TargetId:
                Record.Temp = GetValidFloat ("Enter New Temperature (-10 to 55)", -10, 55)
                Record.Humidity = GetValidFloat ("Enter New Humidity (0 to 100)", 0, 100)
                Record.Rain = GetValidFloat ("Enter New Rainfall (0 to 500): ", 0, 500)
                Record.Status = Record.GetWeatherStatus()
                print("Success! Record updated for", City, "on", Date)
                return
        print("Error: No record found to update.")

    def DeleteRecord(self):
        print("Delete Weather Record")
        Date = GetValidDate()
        City = GetValidCity()
        TargetId = City + "_" + Date

        for Record in self.Records:
            if Record.RecordId == TargetId:
                self.Records.remove(Record)
                print("Successfull! Record deleted for", City , "on" , Date)
                return
        print("Error: No record found to delete")

    def AnalyzeCity(self):
        print("City Weather Statistics")
        City = GetValidCity()
        DicList = []
        for Record in self.Records:
            DicList.append(Record.ToDict())
        CurrentDf = pd.DataFrame(DicList)
        CalculateCityStats(CurrentDf, City)

    def SaveData(self):
        SaveRecordsToCsv(self.Records)

### GUI Dashboard Backend logic codes:

In [51]:
# Intface functions to display the menu and connect user choices to WeatherManager
# These backend codes are the logic for GUI Dashboard Buttons

def DisplayMenu():
    print("Weather Forecast Analyzer of Bangladesh")
    for Option in MenuOptions:
        print(Option)

def RunApplication():
    Manager = WeatherManager()

    while True:
        DisplayMenu()
        Choice = input("Enter your choice (1 to 8): ").strip()

        if Choice == '1':
            Manager.ViewRoceords()
        elif Choice == '2':
            Manager.AddRecord()
        elif Choice == '3':
            Manager.SearchRecord()
        elif Choice == '4':
            Manager.UpdateRecord()
        elif Choice == '5':
            Manager.DeleteRecord()
        elif Choice == '6':
            Manager.AnalyzeCity()
        elif Choice == '7':
            Manager.SaveData()
        elif Choice == '8':
            print("Saving data and closing the program. Goodbye!")
            Manager.SaveData()
            break
        else:
            print("Invalid choice! Please enter a number from 1 to 8.")

In [53]:
RunApplication()

Total records loaded: 14620
Total process finished.
Weather Forecast Analyzer of Bangladesh
1. View Weather Records
2. Add New Weather Record
3. Search Weather Records
4. Update Weather Record
5. Delete Weather Record
6. City Weather Statistics (By NumPy)
7. Save Records to CSV
8. Exit
City Weather Statistics
NumPy Weather Statistics for: Sylhet
Average Temperature: 25.09
Maximum Temperature: 33.04
Minimum Temperature: 13.52
Standard Deviation of  Temperature: 4.2
Total Rainfall: 1824.9
Average Humidity: 82.22
Average Soil Temperature: 24.73

Weather Forecast Analyzer of Bangladesh
1. View Weather Records
2. Add New Weather Record
3. Search Weather Records
4. Update Weather Record
5. Delete Weather Record
6. City Weather Statistics (By NumPy)
7. Save Records to CSV
8. Exit
Saving data and closing the program. Goodbye!
Total records saved 14620
Save Process Finished